### ISSUE TITLE
Direitos de uso e licença em conflito

### ISSUE THREAD

**Issue by matheusfelipeog** [mateusnssp/CursoPython#1]
Olá, @mateusnssp 😆 

No arquivo `README.md` contido na home do seu repositório, na seção **[Direitos de Uso](https://github.com/mateusnssp/CursoPython#direitos-de-uso)**, a condição que você informa entra em conflito direto com o que é proposto na licença **[MIT](https://github.com/mateusnssp/CursoPython/blob/master/LICENSE)** usada no repositório. As unicas condições que são feitas com o uso da licença **MIT** é a citação do autor que criou o projeto e uma copia da mesma licença contida no projeto original. Todo o resto é explicitamente permitido pela licença.

E como arrumar esse conflito?

**Sugestões:**
- Alterar as condições da licença MIT e informar que é uma licença modificada, ou
- Remover a condição proposta no `README.md`, ou
- Remover a licença MIT do repositório, ou
- Aplicar a licença MIT somente em determinados arquivos do repositório e explicitar o escopo da condição proposta no `README.md`, ou
- Alterar para uma outra licença diferente da MIT que entre de acordo com a condição do `README.md`.

Qualquer uma dessas sugestões já revolve o conflito.

**Comment by mateusnssp** [comment]
@matheusfelipeog obrigado por informar! Conflito resolvido! :smile:
